[[main]]
  name = "Notes"
  pageRef = "notes"
  weight = 10

[[main]]
  name = "Writeups"
  pageRef = "writeups"
  weight = 20

[[main]]
  name = "GitHub"
  url = "https://github.com/griffinsectio"
  weight = 30
  [main.params]
    icon = "github"
    showName = false
    target = "_blank"

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"
    icon = "search"

# [[footer]]
#   name = "Privacy"
#   pageRef = "privacy"

